from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(282, 457)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.numberOutput = QtWidgets.QLabel(self.centralwidget)
        self.numberOutput.setGeometry(QtCore.QRect(10, 10, 261, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.numberOutput.setFont(font)
        self.numberOutput.setFrameShape(QtWidgets.QFrame.Box)
        self.numberOutput.setFrameShadow(QtWidgets.QFrame.Raised)
        self.numberOutput.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.numberOutput.setObjectName("numberOutput")
        self.percentButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it('%'))
        self.percentButton.setGeometry(QtCore.QRect(10, 80, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.percentButton.setFont(font)
        self.percentButton.setObjectName("percentButton")
        self.divideButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it('/'))
        self.divideButton.setGeometry(QtCore.QRect(220, 80, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.divideButton.setFont(font)
        self.divideButton.setObjectName("divideButton")
        self.cButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it('C'))
        self.cButton.setGeometry(QtCore.QRect(80, 80, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.cButton.setFont(font)
        self.cButton.setObjectName("cButton")
        self.arrowButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.remove_it())
        self.arrowButton.setGeometry(QtCore.QRect(150, 80, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.arrowButton.setFont(font)
        self.arrowButton.setObjectName("arrowButton")
        self.eightButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it('8'))
        self.eightButton.setGeometry(QtCore.QRect(80, 150, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.eightButton.setFont(font)
        self.eightButton.setObjectName("eightButton")
        self.sevenButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it('7'))
        self.sevenButton.setGeometry(QtCore.QRect(10, 150, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.sevenButton.setFont(font)
        self.sevenButton.setObjectName("sevenButton")
        self.multiplyButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it('*'))
        self.multiplyButton.setGeometry(QtCore.QRect(220, 150, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.multiplyButton.setFont(font)
        self.multiplyButton.setObjectName("multiplyButton")
        self.nineButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it('9'))
        self.nineButton.setGeometry(QtCore.QRect(150, 150, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.nineButton.setFont(font)
        self.nineButton.setObjectName("nineButton")
        self.fiveButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it('5'))
        self.fiveButton.setGeometry(QtCore.QRect(80, 220, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.fiveButton.setFont(font)
        self.fiveButton.setObjectName("fiveButton")
        self.fourButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it('4'))
        self.fourButton.setGeometry(QtCore.QRect(10, 220, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.fourButton.setFont(font)
        self.fourButton.setObjectName("fourButton")
        self.minusButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it('-'))
        self.minusButton.setGeometry(QtCore.QRect(220, 220, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.minusButton.setFont(font)
        self.minusButton.setObjectName("minusButton")
        self.sixButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it('6'))
        self.sixButton.setGeometry(QtCore.QRect(150, 220, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.sixButton.setFont(font)
        self.sixButton.setObjectName("sixButton")
        self.twoButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it('2'))
        self.twoButton.setGeometry(QtCore.QRect(80, 290, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.twoButton.setFont(font)
        self.twoButton.setObjectName("twoButton")
        self.oneButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it('1'))
        self.oneButton.setGeometry(QtCore.QRect(10, 290, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.oneButton.setFont(font)
        self.oneButton.setObjectName("oneButton")
        self.plusButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it('+'))
        self.plusButton.setGeometry(QtCore.QRect(220, 290, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.plusButton.setFont(font)
        self.plusButton.setObjectName("plusButton")
        self.threeButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it('3'))
        self.threeButton.setGeometry(QtCore.QRect(150, 290, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.threeButton.setFont(font)
        self.threeButton.setObjectName("threeButton")
        self.zeroButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it('0'))
        self.zeroButton.setGeometry(QtCore.QRect(80, 360, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.zeroButton.setFont(font)
        self.zeroButton.setObjectName("zeroButton")
        self.plusminusButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.plus_minus_it())
        self.plusminusButton.setGeometry(QtCore.QRect(10, 360, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.plusminusButton.setFont(font)
        self.plusminusButton.setObjectName("plusminusButton")
        self.equalsButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.math_it())
        self.equalsButton.setGeometry(QtCore.QRect(220, 360, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.equalsButton.setFont(font)
        self.equalsButton.setObjectName("equalsButton")
        self.pointButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.dot_it())
        self.pointButton.setGeometry(QtCore.QRect(150, 360, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pointButton.setFont(font)
        self.pointButton.setObjectName("pointButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 282, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def math_it(self):
        screen = self.numberOutput.text()
        number = eval(screen)
        self.numberOutput.setText(str(number))

    def plus_minus_it(self):
        screen = self.numberOutput.text()
        if '-' in screen:
            self.numberOutput.setText(screen.replace('-',''))
        else:
           self.numberOutput.setText(f'-{screen}') 
        

    def remove_it(self):
        screen = self.numberOutput.text()
        screen = screen[:-1]
        self.numberOutput.setText(screen)

    def dot_it(self):
        screen = self.numberOutput.text()
        if screen[-1] == '.':
            pass
        else: 
            self.numberOutput.setText(f'{screen}.')

    def press_it(self, pressed):
        if pressed == 'C':
            self.numberOutput.setText('')
        else: 
            if self.numberOutput.text() == '0':
                self.numberOutput.setText('')
            self.numberOutput.setText(f'{self.numberOutput.text()}{pressed}')


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.numberOutput.setText(_translate("MainWindow", "0"))
        self.percentButton.setText(_translate("MainWindow", "%"))
        self.divideButton.setText(_translate("MainWindow", "/"))
        self.cButton.setText(_translate("MainWindow", "c"))
        self.arrowButton.setText(_translate("MainWindow", "<<"))
        self.eightButton.setText(_translate("MainWindow", "8"))
        self.sevenButton.setText(_translate("MainWindow", "7"))
        self.multiplyButton.setText(_translate("MainWindow", "x"))
        self.nineButton.setText(_translate("MainWindow", "9"))
        self.fiveButton.setText(_translate("MainWindow", "5"))
        self.fourButton.setText(_translate("MainWindow", "4"))
        self.minusButton.setText(_translate("MainWindow", "-"))
        self.sixButton.setText(_translate("MainWindow", "6"))
        self.twoButton.setText(_translate("MainWindow", "2"))
        self.oneButton.setText(_translate("MainWindow", "1"))
        self.plusButton.setText(_translate("MainWindow", "+"))
        self.threeButton.setText(_translate("MainWindow", "3"))
        self.zeroButton.setText(_translate("MainWindow", "0"))
        self.plusminusButton.setText(_translate("MainWindow", "+/-"))
        self.equalsButton.setText(_translate("MainWindow", "="))
        self.pointButton.setText(_translate("MainWindow", "."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
